version: "3.5"
services:
  proxy:
    build: ./proxy
    ports:
      - "8001:8001"
    links:
      - "server"

  server:
    # build:
    #   context: ./v-server
    #   target: build
    build: ./v-server
    ports:
      - "9999:9999"
    volumes:
      - ./v-server:/go/src/v-server
    command: "go run main.go"
    container_name: "server"

  client:
    build: ./v-client
    ports:
      - "8080:8080"
    links:
      - "server"